-- MySQL Script generated by MySQL Workbench
-- Mon Apr  8 16:48:53 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rooms` ;

CREATE TABLE IF NOT EXISTS `rooms` (
  `room_id` INT NOT NULL AUTO_INCREMENT,
  `map_id` INT NOT NULL,
  `name_normal` VARCHAR(45) NOT NULL,
  `name_formal` VARCHAR(45) NOT NULL,
  `mapnode_id` INT NULL,
  PRIMARY KEY (`room_id`),
  UNIQUE INDEX `room_id_UNIQUE` (`room_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maps` ;

CREATE TABLE IF NOT EXISTS `maps` (
  `map_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `building_id` INT NULL,
  `mapfile` VARCHAR(45) NULL,
  `transform_scaling` DECIMAL(16) NULL,
  `transform_offset` DECIMAL(16) NULL,
  `transform_rotation` DECIMAL(16) NULL,
  PRIMARY KEY (`map_id`),
  UNIQUE INDEX `map_id_UNIQUE` (`map_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buildings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buildings` ;

CREATE TABLE IF NOT EXISTS `buildings` (
  `building_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`building_id`),
  UNIQUE INDEX `building_id_UNIQUE` (`building_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barriers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `barriers` ;

CREATE TABLE IF NOT EXISTS `barriers` (
  `barrier_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `barrier_type_id` INT NOT NULL,
  `is_verified` BINARY(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`barrier_id`),
  UNIQUE INDEX `id_barriers_UNIQUE` (`barrier_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barrier_zone_MAP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `barrier_zone_MAP` ;

CREATE TABLE IF NOT EXISTS `barrier_zone_MAP` (
  `barrier_id` INT UNSIGNED NOT NULL,
  `zone` LINESTRING NULL,
  PRIMARY KEY (`barrier_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barrier_type_accessibility_constraints_MAP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `barrier_type_accessibility_constraints_MAP` ;

CREATE TABLE IF NOT EXISTS `barrier_type_accessibility_constraints_MAP` (
  `barrier_type_id` INT NOT NULL,
  `access_constraint_id` INT NOT NULL,
  `weight_default` DECIMAL(10) NULL DEFAULT 500,
  PRIMARY KEY (`barrier_type_id`, `access_constraint_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barrier_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `barrier_types` ;

CREATE TABLE IF NOT EXISTS `barrier_types` (
  `barrier_type_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`barrier_type_id`),
  UNIQUE INDEX `barrier_type_id_UNIQUE` (`barrier_type_id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
